import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Link from 'next/link'
import groq from 'groq'
import client from '../utils/client'


const Home = ({posts}: { posts: any}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h2>Blog Posts</h2>
        {posts.length > 0 && posts.map(
          ({ _id, title = '', slug = '', publishedAt = '' }: { _id: any, title: string, slug: any, publishedAt: string}) => {
            console.log('slug: ', slug);
            return slug && (
              <li key={_id}>
                <Link href="/post/[slug]" as={`/post/${slug.current}`}>
                  <a>{title}</a>
                </Link>{' '}
                ({new Date(publishedAt).toDateString()})
              </li>
            )
          }
        )}
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const posts = await client.fetch(groq`
    *[_type == "post"] | order(publishedAt desc)
  `)
  return {
    props: {
      posts
    }
  }
}

export default Home
