name: deploymentPipeline

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and deploy site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: cd ./studio
      - name: Deploy Sanity
        run: |
          set -e
          SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" yarn sanity deploy
